.travis.yml
pom.xml

* `gauge`
* `terraform`
* `gauge-maven-plugin`
* `gauge-java`

updated gauge and terraform versions

---

.editorconfig
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/specs/01_basic/estimate_gas.spec
src/test/java/com/quorum/gauge/EstimateGas.java

Reverts jpmorganchase/quorum-acceptance-tests#16

Revert "Update gas estimate for low intrinsic gas transactions"

---

src/main/java/com/quorum/gauge/common/RetryWithDelay.java
src/main/java/com/quorum/gauge/ext/IstanbulPropose.java
src/main/java/com/quorum/gauge/ext/MinerStartStop.java
src/main/java/com/quorum/gauge/ext/NodeInfo.java
src/main/java/com/quorum/gauge/services/AccountService.java
src/main/java/com/quorum/gauge/services/IstanbulService.java

Update formatting of some class to make easier to read flow.
Move static classes into own classes along with other "Response" types.

Update formatting and class structure

---

src/main/java/com/quorum/gauge/services/QuorumBootService.java

Dangling reference from updates made in https://github.com/jpmorganchase/quorum-acceptance-tests/pull/19

Update old class reference

---

.github/workflows/run.yml
README.md

- Update github actions workflow to use short message instead of full message when it can not be constructed

add workflow badge to README

---

.github/workflows/run.yml

- Display warning when Github Actions VM is used to run test. This indicates that some tests may fail due to lack of hardware resources
- Fix notification logic in the workflow

fix Github Actions workflow

---

.github/workflows/run.yml
networks/_modules/ignite/main.tf
networks/plugins/main.tf
networks/template/main.tf
networks/typical/main.tf
networks/typical/variables.tf
src/main/java/com/quorum/gauge/Configuration.java
src/main/java/com/quorum/gauge/ext/IstanbulNodeAddress.java
src/main/java/com/quorum/gauge/services/IstanbulService.java
src/specs/02_advanced/istanbul_block_synchronization.spec
src/specs/02_advanced/istanbul_validator_management.spec
src/specs/02_advanced/raft_block_synchronization_with_learner_add_promote.spec
src/specs/02_advanced/raft_block_synchronization_with_learner_quorum.spec
src/test/java/com/quorum/gauge/BlockSynchronization.java
src/test/java/com/quorum/gauge/Istanbul.java
src/test/java/com/quorum/gauge/PublicSmartContract.java

This PR contains spec to verify behaviour of validator and non-validator nodes in istanbul.
It covers the following scenario:
1. propose a validator to become non-validator and verify its not able to seal new blocks but can sync up
2. propose a non-validator node to become validator node and verify its able to seal new blocks and sync up

Add spec to test behaviour of validator and non-validator node in istanbul network

---

networks/plugins/variables.tf
networks/template/main.tf
networks/template/variables.tf
networks/typical/main.tf
networks/typical/variables.tf
src/specs/01_basic/private_smart_contract_async.spec
src/specs/01_basic/private_smart_contract_single.spec
src/specs/02_advanced/transactions_for_block_height.spec

This is helpful when running acceptance tests for a particular Quorum Docker image.
Like running tests for Quorum PRs

allow to set quorum docker image being used

---

.github/workflows/run.yml
pom.xml
src/main/java/com/quorum/gauge/TestSummaryMain.java
src/specs/02_advanced/istanbul_block_synchronization.spec
src/specs/02_advanced/raft_block_synchronization_with_learner_add_promote.spec
src/specs/02_advanced/raft_block_synchronization_with_learner_quorum.spec
src/specs/02_advanced/raft_block_synchronization_with_peer.spec
src/specs/concepts/new_network_node.cpt
src/specs/concepts/new_network_node_with_gcmode.cpt
src/test/java/com/quorum/gauge/BlockSynchronization.java

Make sure legit scenarios not being skipped due to changes in their names

revive skipped tests due to scenario names changed

---

.github/workflows/publish_docker_image.yml

- make sure we match correctly Github Actions status so Slack message
reflects the same
- docker repo name must be lowercase

fix job status matching and Github Packages repo name

---

src/main/java/com/quorum/gauge/services/AccountService.java

in order to support 7-nodes example run

fix default account logic

---

.github/workflows/run.yml

With secrets `SCHEDULE_RUN=disable`, workflow will not run for schedule event

allow to skip schedule run via GithubActions secret

---

src/test/java/com/quorum/gauge/PrivateSmartContract.java

In `When there's an update, privacy is still enforced` test scenario, we invoke `eth_call` in another node without checking the transaction receipt. This causes intermittent failures as the local private state has not been updated yet.

Fix eventual consistency issue in privacy test scenarios

---

src/test/java/com/quorum/gauge/Permissions.java

This PR removes hard coded wait times in the acceptance test for permissions model.

permissions acceptance test code clean up

---

README.md

Adding some clarification on how to install the terraform provider for running tests locally, as it's not clear from the terraform docs.

Clarify installation of the terraform provider

---

.gitignore
src/specs/01_basic/qe81_non_party_transactions.spec
src/specs/01_basic/qe81_private_state_validation.spec

* Handle new EVM error message as changed by https://github.com/ethereum/go-ethereum/pull/20830, in the GoQuorum go-ethereum v1.9.14 upstream upgrade.
* Add *.iml files to gitignore.
* https://github.com/ConsenSys/quorum/pull/1130

Fix EVM error message handling

---

networks/plugins/main.tf

- use https://provisional-plugins-repo.quorum.consensys.net

configure proxy url for plugin central

---

Dockerfile
pom.xml

Reverts ConsenSys/quorum-acceptance-tests#112
We need to test better a situation before merging. Avoiding to make other people blocked.

Revert "Update OpenJDK and Gauge"

---

networks/_modules/docker-besu/besu.tf

Signed-off-by: Stefan Pingel <stefan.pingel@consensys.net>

remove besu CLI option

---

Dockerfile

By copying the `pom.xml` + `manifest.json` first and compiling in another step, we don't have to redownload all dependencies if we didn't modify any deps in the pom and manifest.

improve caching of deps during docker build

---

networks/_modules/ignite/bootstrap.tf
networks/_modules/ignite/main.tf
networks/_modules/ignite/variables.tf
networks/plugins/main.tf
networks/template/main.tf
networks/typical/main.tf

From review comments on https://github.com/ConsenSys/quorum-acceptance-tests/pull/111

Fix formatting and typos

---

networks/_modules/docker-besu/tessera.tf
networks/_modules/docker/tessera.tf

[Tessera PR 1307](https://github.com/ConsenSys/tessera/pull/1307) will update the location of the executable script in the Tessera images to `/tessera/bin/tessera`

Update tessera setup to use updated bin location

---

.github/workflows/run.yml
src/main/java/com/quorum/gauge/common/RawDeployedContractTarget.java
src/main/java/com/quorum/gauge/services/RawContractService.java
src/specs/01_basic/private_raw_smart_contract_spam.spec
src/test/java/com/quorum/gauge/PrivateSmartContract.java

* Added a spam test of sending multiple raw private transaction between different nodes which is being signed externally
* Verify that the value stored in the simple storage contract match the randomly generated one 
* Run the new spam raw private transaction test against besu network

Spam test for send raw private transaction

---

.github/workflows/run.yml

`eth_getQuorumPayload` is now supported by Besu.

Enable eth_getQuorumPayload tests for Besu

---

networks/typical-hybrid/main.tf
networks/typical-hybrid/remote_docker.tf

Updated remote docker scp directories for besu, quroum, ethsigner and tessera to fix aws failures

Updated remote docker scp directories

---

pom.xml
src/main/java/com/quorum/gauge/services/SocksProxyEmbeddedServer.java

security: fix vulnerability for org.apache.sshd:sshd-core

---

pom.xml
src/main/java/com/quorum/gauge/services/SocksProxyEmbeddedServer.java

#126 causing SockProxy failures
This reverts commit d113c3b157e3b9943e18ebd9cceb2043019f9da4.

Revert "security: fix vulnerability for org.apache.sshd:sshd-core"

---

networks/_modules/docker/geth.tf
networks/_modules/ignite/bootstrap.tf
src/main/java/com/quorum/gauge/services/DebugService.java
src/specs/02_advanced/mps_db_upgrade_private_state_root_check.spec
src/test/java/com/quorum/gauge/Debug.java
src/test/java/com/quorum/gauge/PENetworkUpgrade.java

**Changes**
- new mpsdbupgrade scenario
- client API to retrieve the `defaultStateRoot`

mpsdbupgrade: add standalone node db upgrade scenario

---

networks/template/terraform.istanbul-4nodes-pe.tfvars
networks/template/terraform.raft-4nodes-pe.tfvars
src/main/java/com/quorum/gauge/services/DockerInfrastructureService.java
src/specs/02_advanced/qe81_network_upgrade.spec

upgrade go-quorum from 2.5.0 to 21.10.0 then to the latest develop version

fix test for geth 1.10 upgrade

---

networks/_modules/docker-helper/variables.tf
networks/typical-besu/variables.tf
networks/typical-hybrid/variables.tf

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

changed to consensys/ethsigner docker and use latest tag

---

.github/workflows/run.yml
networks/template/terraform.istanbul-4nodes-mps-pmt.tfvars
networks/template/terraform.raft-4nodes-mps-pmt.tfvars
src/main/java/com/quorum/gauge/services/DebugService.java
src/specs/02_advanced/mps_pmt_mixed_network_private_state_root_check.spec
src/test/java/com/quorum/gauge/Debug.java

Add tests to check private state roots for MPS/non MPS nodes with PMT enabled and verify that the precompile contract does not exist in the private state.

Check private state roots for MPS/non MPS nodes with PMT enabled

---

networks/typical-besu/variables.tf

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
Need the docker image published to try this out with Besu CI platform. Will be reverted if that testing fails

try tessera 22.1.6

---

src/main/java/com/quorum/gauge/services/RawContractService.java
src/specs/01_basic/private_raw_smart_contract_spam.spec

- the transaction hash is lost on the retry somewhere in rx code

Wait for for each receipt first
