src/specs/01_basic/private_smart_contract_multiple.spec
src/specs/02_advanced/private_transaction_bloom_section.spec
src/test/java/com/quorum/gauge/PrivateSmartContract.java
src/test/java/com/quorum/gauge/PublicSmartContract.java
src/test/java/com/quorum/gauge/core/AbstractSpecImplementation.java

this is to cover PR https://github.com/jpmorganchase/quorum/pull/570
The idea is to keep on generating blocks until block height is more than certain threshold to trigger `ChainIndexer` to index current bloom section. During the indexing, the private bloom is not included therefore the bug.
Each bloom section contains 4096 blocks and there's an additional of 256 blocks for bloom confirmations before the section is indexed.
Using `raft` will help us to generate blocks faster to verify the spec

added specs to cover PR jpmorganchase/quorum/#570

---

pom.xml
src/specs/01_basic/externally_signed_private_raw_smart_contract_single.spec

Removed snapshot repo from pom (as we are no longer using a snapshot build for the web3j.quorum library)

uptick the web3j.quorum library after the 4.0.6 release

---

src/specs/01_basic/estimate_gas.spec
src/specs/01_basic/raft_gas_usage.spec

Updating the gas values in some tests. Needed due to change in quorum-examples to enable homestead (which changes the gas usage).
These changes must be merged at the same time as the related PR in quorum-examples (https://github.com/jpmorganchase/quorum-examples/pull/162).

Updating the gas values in some tests. Needed due to change in quorum-examples.

---

.editorconfig
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/specs/01_basic/estimate_gas.spec
src/test/java/com/quorum/gauge/EstimateGas.java

Adds a test to run the transaction using the gas estimate returned and check it succeeds.
Previous behaviour estimated the cost of the transaction but never submitted it, and in this case it ran out of gas due to intrinsic gas differences between public and private gas costs.
Depends on https://github.com/jpmorganchase/quorum/pull/644
<hr>
Also contains a few formatting changes and a `.editorconfig` file to keep formatting similar between user IDEs.

Update gas estimate for low intrinsic gas transactions

---

.editorconfig
README.md
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/specs/01_basic/estimate_gas.spec
src/test/java/com/quorum/gauge/EstimateGas.java

Resubmit for PR #16 
---
Adds a test to run the transaction using the gas estimate returned and check it succeeds.
Previous behaviour estimated the cost of the transaction but never submitted it, and in this case it ran out of gas due to intrinsic gas differences between public and private gas costs.
Depends on https://github.com/jpmorganchase/quorum/pull/644
---
Also contains a few formatting changes and a `.editorconfig` file to keep formatting similar between user IDEs.

Update gas estimate for low intrinsic gas transactions #16

---

src/main/java/com/quorum/gauge/services/IstanbulService.java
src/specs/01_basic/estimate_gas.spec
src/specs/01_basic/estimate_gas_private.spec
src/test/java/com/quorum/gauge/PublicSmartContract.java

Split the gas estimate tests into public and private tests. This is to avoid having scenarios for deploying contracts specific to other scenarios, which should be part of spec setup.
Make use of existing step methods for deploying contracts.

Split public and private gas estimate tests

---

src/main/java/com/quorum/gauge/common/QuorumNetworkConfiguration.java
src/main/java/com/quorum/gauge/services/AbstractService.java
src/main/java/com/quorum/gauge/services/RawContractService.java
src/main/java/com/quorum/gauge/services/TransactionService.java
src/test/java/com/quorum/gauge/SmartContractDualState.java

A few general updates
- remove unneeded generics from collection types
- removed unneeded warning suppressions
- simplified returns
- switched the StringBuffer to StringBuilder as thread sync is not needed

Remove generic types when not needed

---

pom.xml
src/main/java/com/quorum/gauge/common/RetryWithDelay.java
src/main/java/com/quorum/gauge/services/AccountService.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/main/java/com/quorum/gauge/services/IstanbulService.java
src/main/java/com/quorum/gauge/services/QuorumBootService.java
src/main/java/com/quorum/gauge/services/RaftService.java
src/main/java/com/quorum/gauge/services/RawContractService.java
src/main/java/com/quorum/gauge/services/TransactionService.java
src/main/java/com/quorum/gauge/services/UtilService.java
src/test/java/com/quorum/gauge/BlockSynchronization.java
src/test/java/com/quorum/gauge/EstimateGas.java
src/test/java/com/quorum/gauge/Istanbul.java
src/test/java/com/quorum/gauge/PrivateRawSmartContract.java
src/test/java/com/quorum/gauge/PrivateRawSmartContractEthApi.java
src/test/java/com/quorum/gauge/PrivateSmartContract.java
src/test/java/com/quorum/gauge/PublicRawSmartContract.java
src/test/java/com/quorum/gauge/PublicSmartContract.java
src/test/java/com/quorum/gauge/RaftGasUsage.java
src/test/java/com/quorum/gauge/SmartContractDualState.java
src/test/java/com/quorum/gauge/ValueTransferPrivateTransaction.java
src/test/java/com/quorum/gauge/ValueTransferPublicTransaction.java
src/test/java/com/quorum/gauge/core/AbstractSpecImplementation.java
src/test/java/com/quorum/gauge/core/ExecutionHooks.java

Update use of the Reactive library, which is bundled in Web3j, to use the updated APIs.
This is caused from moving from version 1.x to 2.x.
The bulk of the change is around converting from "Flowable"s to "Observable"s, and converting ".blocking().first()" to the new single method ".blockingFirst()".
Note: the versions upgraded to here are not the latest versions. `web3j-maven-plugin` does not seem to be updated anymore, favouring an equivalent Gradle plugin. The versions of other libraries here are the last compatible versions with the maven plugin. We might look to move to Gradle instead, or see if we can use the Gradle plugin in maven.

Upgrade web3j dependencies to latest compatible versions

---

.travis.yml
pom.xml
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/common/QuorumNode.java
src/main/java/com/quorum/gauge/common/QuorumNodeParameterParser.java
src/main/java/com/quorum/gauge/services/QuorumNodeConnectionFactory.java
src/main/java/com/quorum/gauge/services/TransactionService.java
src/test/java/com/quorum/gauge/EstimateGas.java
src/test/java/com/quorum/gauge/core/ExecutionHooks.java

A custom parser gets access to the configuration properties to be able to identify which node is being talked about and pull the correct config without it needing to be tied to a static enum. This will allow a variable number of nodes without needing extra config (such as adding more enum values at compile time) or being limited by them (the number if enum values specified is a hard limit for the test).
An update to the latest version of Gauge is also required (or at least higher than version 1.0.4 which was previously used) to allow the use of the Java plugin v0.7.4.
This PR repurposes one of the tests to show how it can be used.

Allow nodes to be specified by name without needing the enum

---

pom.xml
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/services/PrivacyService.java

* QuorumNetworkProperty now supports aliases for privace addreses.
This help to parameterize scenarios without knowing the explicit value.
* Spring Boot 2.2.6 fixes an issuue when externalizing
`spring.config.additional-location` via environment variable.
It now can accept `SPRING_CONFIG_ADDITIONALLOCATION`. This is crucial
when we customize the networks and require Spring Boot to load
application.yml from a dedicated location

add support for privacy address aliases and upgrade spring boot

---

.github/workflows/run.yml

- Test reports are stored in the output directory along with Quorum
network generated resources. This folder is uploaded as a Github Actions
workflow artifact whose size is very big. Indeed, we only need test
reports to be able to aggregate test summary.

update Github Actions to reduce artifact size

---

.github/workflows/run.yml
pom.xml

`--fail-safe` causes the `mvn` build to succeed even if tests failed.  This is required for the current CI setup for the acceptance test suite.  However this behaviour is non-standard and therefore would likely be unexpected by users of the acceptance-test project.
The `mvn` build will now fail by default if there are any test failures, so that the user receives explicit feedback on the test results.  If the `--fail-safe` behaviour is required it can be explicitly enabled with the `gaugeFailSafe` `mvn` profile.
**Note:** *Any existing CI setups that require the `--fail-safe` behaviour will obviously have to be updated to use the profile once this change is made*

Disable --gauge-fail-safe by default and add mvn profile toggle

---

.github/workflows/run.yml
Dockerfile
pom.xml

in the following:
- Gauge java plugin for gauge runtime
- Gauge java dependency in pom.xml
Also optimize `Dockerfile` for parallel downloading and error handling
Note: 0.7.8 doesn't give a consistent run so we use 0.7.7 now

use the same Gauge java version

---

Dockerfile
README.md
pom.xml
src/main/java/com/quorum/gauge/services/DockerInfrastructureService.java

- update docker-java to 3.2.2 which provides official support for Apache
HTTPClient 5 transport
- update quickstart in README to use `auto.outputDir` which is required to store the network resources which then
be used to mount to the containers
- clean up Dockerfile

update docker-java dependency and Docker related files 

---

src/test/java/com/quorum/gauge/NestedPrivateContract.java
src/test/java/com/quorum/gauge/Permissions.java

This PR fixes the random error seen while executing permissions test cases:
```
Failed Step: Get network details from <node>
Specification: src/specs/02_advanced/enhanced_permissions_model.spec
Error Message: java.lang.RuntimeException: java.io.IOException: unexpected end of stream on http://localhost:22003/...
Stacktrace: 
```
The PR also fixes the below error:
```
Failed Step: Transaction Receipt is <status> available in <nodeList> for <contractName>
Specification: src/specs/02_advanced/enhanced_permissions_model.spec
Error Message: java.lang.AssertionError: [Value class for key [blocknumber] in Gauge DataStore] 
Expecting actual not to be null
Stacktrace: 
```

Fix random failure of permissions test cases

---

.github/workflows/run.yml
networks/plugins/files.tf
networks/plugins/plugin-hello-world.tf
networks/plugins/plugin-security.tf
networks/plugins/terraform.istanbul-rpc-security.tfvars
networks/plugins/terraform.istanbul.tfvars
networks/plugins/terraform.raft-rpc-security.tfvars
src/main/java/com/quorum/gauge/Configuration.java
src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/ext/BatchRequest.java
src/main/java/com/quorum/gauge/ext/BatchResponse.java
src/main/java/com/quorum/gauge/services/AbstractService.java
src/main/java/com/quorum/gauge/services/OAuth2Service.java
src/main/java/com/quorum/gauge/services/RPCService.java
src/specs/02_advanced/plugin_security.spec
src/test/java/com/quorum/gauge/PluginSecurity.java
src/test/java/com/quorum/gauge/PrivateSmartContract.java
src/test/java/com/quorum/gauge/PublicSmartContract.java
src/test/java/com/quorum/gauge/core/AbstractSpecImplementation.java
src/test/java/com/quorum/gauge/core/BootSpring.java
src/test/java/com/quorum/gauge/core/ExecutionHooks.java

- Network setup for plugin security creates an additional container which
represents an OAuth2 Authorization Server. We use ory/hyrda to achive
this.
- Spring Active Profiles contain additional one: security. application-plugins.yml
is created by networks/plugins when security plugin is configured.
- QuorumNetworkProperty now contains endpoints in order to communicate
with the authorization server.
- Introduce BatchRequest and BatchResponse to extend web3j functionality

add plugin security specs and glue code implementation

---

.github/workflows/run.yml
README.md

The workflow `run.yml` is bloated with tools and env setup which duplicates those in `Dockerfile`.
https://github.com/jpmorganchase/quorum-acceptance-tests/blob/41f6835f64ad836c58fb27edb2266964be3a1d82/Dockerfile#L3-L10
This PR is to remove this duplication and centralize the updates in `Dockerfile` only by building Docker image prior running the suite. Docker image is built once and cached to improve the total execution time.

run tests using Docker

---

src/main/java/com/quorum/gauge/services/HashicorpVaultAbstractService.java
src/specs/02_advanced/account_plugin_hashicorpvault_creation.spec
src/specs/02_advanced/account_plugin_hashicorpvault_signing.spec
src/test/java/com/quorum/gauge/PluginHashicorpVaultAccountSigning.java

* **Create SSL-enabled vault client from spring-managed okhttpclient**
When running tests on AWS this ensures the vault client is configured with the necessary proxy to communicate with AWS resources
* **Remove tests which check implementation specific functionality of the vault account plugin**
This is the first part of a refocusing of the account plugin section of the quorum-acceptance-tests on quorum functionality and to move any plugin implementation specific tests to the corresponding plugin's repo - thereby simplifying the quorum-acceptance-tests and making the tests plugin agnostic.
This removes the need to test the filesystem for the creation of Vault plugin files, something which is already tested in the plugin's own set of tests

vault: fixes for AWS, reduce testing of plugin impl-specific functionality

---

networks/_modules/docker/variables.tf
networks/_modules/docker/waithook.tf
src/test/java/com/quorum/gauge/PrivateSmartContract.java

Previously we depend on waithook.com to verify the callback when calling
`sendTransactionAsync` API. However the service is not stable and
currently down causing tests failing.
This is to use the same codebase used in waithook.com and run in a
container to provide same mechanism used in the test

remove external service dependency when running async tests

---

src/test/java/com/quorum/gauge/PrivateSmartContract.java

when using socks5 proxy, customizing `OkHttpClient` dns resolver causes
websocket fail to initialize. Using explicit hostname in the URL is a
simpler way to make this work.

use explicit hostname instead of having customized Dns for HTTP client

---

src/specs/02_advanced/qe81_network_upgrade.spec
src/test/java/com/quorum/gauge/PENetworkUpgrade.java

While running the network upgrade scenario using raft the quorum process panics when it gets into a BadBlock state (caused by receiving a privacy enhanced transaction while privacy enhancements are disabled).
The tests then check that the state of the quorum container is down.
When running on AWS it seems there is some delay between the quorum process dying and the state of the docker container being reported as down. The test was updated to wait for the container to reach the state rather than just check current container state.

Improve pe network upgrade test stability

---

.github/workflows/publish_docker_image.yml
.github/workflows/run.yml

- retire add-path and set-env commands being used in Github Actions workflows
- use ubuntu-18.04 consistently for builds

fix Github Actions workflows deprecation warnings

---

src/main/java/com/quorum/gauge/services/TransactionService.java
src/specs/02_advanced/qe81_network_upgrade.spec
src/test/java/com/quorum/gauge/BlockSynchronization.java

As while we get the block number before stoping a Node, the node might jump to the next one while is shutting down, which leads to us having an older one. if we use this to then activate the privacy enhancements (a block above), we might still have an old block number to activate the features for.
This fix by using the block number from another node to be sure that we use a future one to activate the privacy enhancements. Thanks @nicolae-leonte-go for the help.
* Do a second get of the block number after stopping Node1 in the test `Partial Network upgrade from an old version (q2.5.0/t0.10.5) to privacy enhancements enabled version of geth and tessera`
* Increase the number of times we get the receipt, as locally on MacOS 30 times seems not enough (@nicolae-leonte-go please confirm if …

[Fix] Use the right network block number to activate privacy enhancements

---

src/main/java/com/quorum/gauge/common/QuorumNetworkProperty.java
src/main/java/com/quorum/gauge/common/QuorumNodeListParameterParser.java
src/main/java/com/quorum/gauge/common/QuorumNodeParameterParser.java
src/main/java/com/quorum/gauge/services/AccountService.java
src/main/java/com/quorum/gauge/services/GraphQLService.java
src/main/java/com/quorum/gauge/services/PrivacyService.java
src/main/java/com/quorum/gauge/services/QuorumNodeConnectionFactory.java
src/main/java/com/quorum/gauge/services/RaftService.java
src/test/java/com/quorum/gauge/MultiTenancy.java
src/test/java/com/quorum/gauge/PluginSecurity.java

As the `QuorumNode` enum type is deprecated to allow custom node names, this switches the default type that configuration uses to name the nodes.
Places that still need the QuorumNode can use the helper method to convert.

Switch default node type in configuration

---

src/main/java/com/quorum/gauge/ext/EnhancedClientTransactionManager.java
src/main/java/com/quorum/gauge/services/AbstractService.java
src/main/java/com/quorum/gauge/services/ContractCodeReaderService.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/main/java/com/quorum/gauge/services/NestedContractService.java
src/main/java/com/quorum/gauge/services/PermissionsContractService.java
src/main/java/com/quorum/gauge/services/PrivacyService.java
src/main/java/com/quorum/gauge/services/RawContractService.java
src/main/java/com/quorum/gauge/services/StorageMasterService.java

Most of the types TransactionManagers created use the default settings for timeout and retry count, so added convenience methods for creating these to reduce the amount of noise they make in amongst the test code.
Also added a convenience method for converting node names to Tessera Keys, so reduce the amount of inline streams, which can clutter up the method calls.

Remove repeated timeout/retry defaults and factor out common ops

---

networks/_modules/docker/ethstats.tf
networks/_modules/docker/geth.tf
networks/_modules/docker/variables.tf

- Pulling `ethstats` Docker image often fails. When running in Github Acttions, we don't need `ethstats`
- `ethstats` can be enabled by setting variable `enable_ethstats` to true

improve stability while running in Github Actions

---

.gitignore
Dockerfile
README.md
networks/_modules/docker/outputs.tf
networks/_modules/docker/versions.tf
networks/_modules/ignite/main.tf
networks/plugins/hashicorp-vault.tf
networks/plugins/main.tf
networks/plugins/plugin-security.tf
networks/plugins/versions.tf
networks/template/versions.tf
networks/typical/versions.tf
src/specs/01_basic/fill_transaction.spec

- Migrate to support terraform 0.14.7
- Source Terraform Provider Quorum from Terraform Registry instead of manual download

upgrade Terraform and Quorum Provider

---

src/main/java/com/quorum/gauge/ext/EnhancedClientTransactionManager.java
src/main/java/com/quorum/gauge/services/ContractService.java

There is an issue where the AT are sending `privacyFlag` argument when is a Public Tx.
* Fix the issue by checking if the target privateTo is `null`. on that case, we shouldn't send a `privacyFlag`

Remove privacyFlags and privateTo array if not sent.

---

Dockerfile
extra/solcJ-all-0.4.25.pom
pom.xml

- `web3j-maven-plugin` has runtime dependency on `solcJ-all` jar which is stored in ethereum maven repo which is hosted in Bintray
- As Bintray is going to be sunset, we store `solcJ-all` jar locally to avoid downloading from Bintray
Note:
- I tried to update the `web3j-maven-plugin` but the code generation is buggy and unpredictable
- This PR is considered as a workaround solution for the time being

fix `web3j-maven-plugin` dependency on Ethereum maven repo in Bintray

---

Dockerfile
networks/plugins/terraform.istanbul-rpc-security.tfvars
networks/plugins/terraform.raft-rpc-security.tfvars
src/main/java/com/quorum/gauge/common/RetryWithDelay.java

- when retrying happens, a different thread is used so access token value must be retained
- fix Dockerfile not to `skipGenerateSol` as Permission spec needs to selectively compile the right Solidity code

fix flaky RPC test due to retry logic not having access token

---

networks/plugins/main.tf

- randomize the plugin central configuration so some nodes use the proxy and some use the default configuration
Depends on https://github.com/ConsenSys/quorum/pull/1174

plugin: cover both default and proxy configuration

---

networks/_modules/docker-besu/tessera.tf
networks/_modules/docker/tessera.tf

During development of the Tessera Jigsaw impl (https://github.com/ConsenSys/tessera/pull/1200), the entrypoint used to start Tessera is different, but this is overriden in the Terraform scripts.
This PR adds a temporary solution by defaulting to the existing jar file (or one the user specifies), and if it doesn't exist, then uses the location expected for the Jigsaw dist.
Once the Tessera changes are merged, this change can be updated to default to the start script or the user defined location.
Note: the start script that the Jigsaw dish uses is actually just the gradle generated start script.

Update Tessera start command

---

src/specs/01_basic/estimate_gas.spec

Update as per fix done on https://github.com/ConsenSys/quorum/pull/1195.
NOTE: already tested locally but on the pipeline won't get green that test as fix is not yet merged in GoQ (it will only be merged after).
* Change the public estimated gas to match the Istanbul fork when a tx value is 0 and could contain a PTM hash.

[Fix] update public tx estimation to the right one post istanbul

---

.github/workflows/run.yml
src/specs/01_basic/private_smart_contract_spam.spec

As ethSigner doesn't support well handling the nonce management, we are skipping this test for Besu.
* Add new `spam` tag
* Ignore the `spam` tag from the Besu CI/CD job.

Ignore spam tests for Besu

---

Dockerfile

When running tests, there are few dependencies being downloaded.
Occassionally Github Actions disconnects while downloading such
dependencies causing the workflow error.
This is to make sure we cache all necessary dependencies in the Docker
image to avoid such instability like above.

cache other dependencies

---

.github/workflows/run.yml
networks/template/terraform.istanbul-4nodes-ancientdb.tfvars
networks/template/terraform.raft-4nodes-ancientdb.tfvars
src/main/java/com/quorum/gauge/services/UtilService.java
src/specs/02_advanced/network_migration_ancientdb.spec
src/test/java/com/quorum/gauge/BlockSynchronization.java
src/test/java/com/quorum/gauge/NetworkMigration.java

This test replicates this issue https://github.com/ConsenSys/quorum/issues/1179.
* Added a new test with a low immutability threshold to force the client to move data to the freezer db.
* Test after migration that we can still access blocks saved on the freezer db.

Add new AT that tests the network migration with freezerdb data

---

.github/workflows/run.yml
networks/_modules/docker-helper/variables.tf
networks/typical-besu/variables.tf
src/test/java/com/quorum/gauge/PrivateStateValidation.java

* Remove ignore job from the GithubAction configuration on Quorum Acceptance tests project to make the job fail when the tests fail
* Update Besu, EthSigner and Tessera tags to `develop`.
* Reduce flakiness

ci/cd: make Besu network fail if tests fail, remove the skip checks

---

.github/workflows/run.yml
networks/_modules/docker-besu/besu.tf
networks/_modules/docker-besu/ethsigner.tf
networks/_modules/docker-besu/main.tf
networks/_modules/docker-besu/tessera.tf
networks/_modules/docker-besu/variables.tf
networks/_modules/ignite-besu/main.tf
networks/_modules/ignite-besu/outputs.tf
networks/_modules/ignite-besu/variables.tf
networks/typical-hybrid/bootstrap.tf
networks/typical-hybrid/files.tf
networks/typical-hybrid/main.tf
networks/typical-hybrid/terraform.hybrid-template-q1b2.tfvars
networks/typical-hybrid/terraform.hybrid-template-q2b1.tfvars
networks/typical-hybrid/variables.tf
src/main/java/com/quorum/gauge/ext/NodeInfo.java
src/main/java/com/quorum/gauge/services/BesuQBFTService.java
src/main/java/com/quorum/gauge/services/DockerInfrastructureService.java
src/main/java/com/quorum/gauge/services/InfrastructureService.java
src/main/java/com/quorum/gauge/services/IstanbulService.java
src/main/java/com/quorum/gauge/services/UnsupportedInfrastructureService.java
src/main/java/com/quorum/gauge/services/UtilService.java
src/specs/02_advanced/hybrid_validator_management_manage_besu.spec
src/specs/02_advanced/hybrid_validator_management_manage_quorum.spec
src/specs/02_advanced/istanbul_block_synchronization.spec
src/specs/02_advanced/istanbul_validator_management.spec
src/test/java/com/quorum/gauge/BlockSynchronization.java

* Add validator management test for hybrid network. 
* `hybrid_validator_management_manage_besu.spec` tests validator management by adding/removing besu node and checks if the network performs fine
* `hybrid_validator_management_manage_quorum.spec` tests validator management by adding/removing quorum node and checks if the network performs fine
* Templating support has been added to the `typical-hybrid` module using `terraform.hybrid-template-q1b2.tfvars` and `terraform.hybrid-template-q2b1.tfvars`

Hybrid validator management

---

.github/workflows/run-extra.yml
src/main/java/com/quorum/gauge/common/PrivacyFlag.java
src/main/java/com/quorum/gauge/ext/EnhancedClientTransactionManager.java
src/main/java/com/quorum/gauge/services/ContractService.java
src/main/java/com/quorum/gauge/services/NestedContractService.java
src/specs/01_basic/mandatory_recipients.spec
src/test/java/com/quorum/gauge/MandatoryRecipients.java

- Add `MandatoryRecipients(2)` privacy flag
- Update `EnhancedClientTransactionManager` to send transactions with mandatory recipients
- Test specs for mandatory recipients

Tests for mandatory recipients

---

src/main/java/com/quorum/gauge/services/DockerInfrastructureService.java

Require `healthy` status only for wait condition of docker container. If max number of retry is reached, return non ready.

modify wait condition for container, require healthy status

---

Dockerfile

- switching to alpine:edge for now
- this could be switch back at a later date

For some reason openjdk-14 is not available in alpine:latest (3.14)

---

networks/_modules/docker-besu/ethsigner.tf
networks/_modules/docker-helper/variables.tf
networks/_modules/ignite-besu/bootstrap.tf
networks/typical-besu/variables.tf
networks/typical-hybrid/bootstrap.tf
networks/typical-hybrid/variables.tf

-- Change v3 keystore file to world readable so that ethsigner container can
read it
-- Revert ethsigner container to use develop
-- Remove netcat manual installation in ethsigner docker definition as
it required root user. It will be available via original image instead.

Fix Ethsigner to run with non-root user

---

networks/typical-besu/variables.tf

Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>
Seeing this error in besu CI 
```
2022-08-19 19:14:41.104  INFO 481 --- [           main] com.quorum.gauge.DockerWaitMain          : /run-at-besu-node0(b3f94df194a5): status = running, health = starting, dead = false, ongoing = true
2022-08-19 19:14:41.124  INFO 481 --- [           main] com.quorum.gauge.DockerWaitMain          : /run-at-besu-tm0(daec3e08fbe1): status = exited, health = unhealthy, dead = true, ongoing = true
2022-08-19 19:14:41.125  INFO 481 --- [           main] com.quorum.gauge.DockerWaitMain          : /run-at-besu-tm0(daec3e08fbe1) IS DEAD: status = exited, health = unhealthy, dead = true, ongoing = true
STDOUT: Tessera Besu 1
STDERR: /bin/sh: 6: //: Permission denied
STDERR: /bin/sh: 9: [[: not found …
```

revert version of tessera to see if that fixes error

---

networks/_modules/ignite-besu/main.tf
networks/_modules/ignite/main.tf

Warning: Argument is deprecated Use numeric instead
Signed-off-by: Sally MacFarlane <sally.macfarlane@consensys.net>

number (deprecated) -> numeric

---

networks/_modules/docker-besu/besu.tf

the new default is quite restrictive, and will change asap the new txpool version in besu, but for the time being you set this parameter --tx-pool-limit-by-account-percentage=1
Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
Should fix this error eg https://app.circleci.com/pipelines/gh/hyperledger/besu/18550/workflows/13770429-8ae2-4ddb-ba06-882df690df1a/jobs/112954
```
https://github.com/ReactiveX/RxJava/wiki/What's-different-in-2.0#error-handling | org.web3j.protocol.exceptions.TransactionException: JsonRpcError thrown with code -32000. Message: Transaction nonce it too distant from current sender nonce
at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:367)
at io.reactivex.internal.operators.flowable.FlowableFromCallable.subscribeActual(FlowableFromCallable.ja …
```

increase limit for tx pool future nonces

---

networks/_modules/docker-besu/besu.tf

Signed-off-by: Sally MacFarlane <macfarla.github@gmail.com>
--tx-pool-limit-by-account-percentage=5
since we are still getting the error 
```
Failed Step: Execute "contract12"'s `deposit()` function "10" times with arbitrary id and value from "Node1"
Specification: src/specs/01_basic/public_smart_contract_event.spec:28
Error Message: java.lang.RuntimeException: org.web3j.protocol.exceptions.TransactionException: JsonRpcError thrown with code -32000. Message: Transaction nonce it too distant from current sender nonce
```

besu - increase max percentage of tx pool again
